name: Deploy to Server (transyainsa - git pull)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via git pull on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}              # ej: 148.230.93.19
          username: ${{ secrets.SSH_USER }}          # ej: root o deploy
          port: ${{ secrets.SSH_PORT || '22' }}      # si no pones secret, usa 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}        # clave privada para entrar al servidor
          script_stop: true
          script: |
            set -euo pipefail

            REPO_SSH="git@github.com:bryan2709/transyainsa.git"
            APP_DIR="${{ secrets.DEPLOY_PATH }}"

            # Preparar SSH del servidor para hablar con GitHub
            mkdir -p ~/.ssh && chmod 700 ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts

            # Crear carpeta de la app si no existe
            mkdir -p "$APP_DIR"
            cd "$APP_DIR"

            # Clonar/actualizar repo
            if [ ! -d .git ]; then
              git init
              git remote add origin "$REPO_SSH" || true
              git fetch origin main
              git checkout -B main origin/main
            else
              git fetch origin main
              git reset --hard origin/main
              git clean -fd
            fi

            # Composer (instala si no existe)
            if ! command -v composer >/dev/null 2>&1; then
              php -r "copy('https://getcomposer.org/installer','composer-setup.php');"
              php composer-setup.php --install-dir=/usr/local/bin --filename=composer
              rm -f composer-setup.php
            fi

            # Dependencias PHP
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

            # Caches de Laravel (descomenta migraciones si corresponde)
            php artisan config:cache || true
            php artisan route:cache || true
            php artisan view:cache || true
            # php artisan migrate --force || true

            # Frontend si aplica
            if [ -f package.json ]; then
              if ! command -v npm >/dev/null 2>&1; then
                curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
                apt-get update && apt-get install -y nodejs
              fi
              npm ci
              npm run build
            fi

            # Permisos Laravel
            chown -R www-data:www-data storage bootstrap/cache || true
            chmod -R ug+rw storage bootstrap/cache || true

            # Reload del web server
            systemctl reload apache2 2>/dev/null || systemctl reload nginx 2>/dev/null || true
